import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :project_social_networks, ProjectSocialNetworksWeb.Endpoint,
  check_origin: [
    "https://preneur-social-v3.onrender.com",
    "//preneur-social-v3.onrender.com",  # Alternativa sin esquema
    "http://localhost:4000"
  ],
  live_view: [
    signing_salt: System.get_env("LIVE_VIEW_SALT"),
    allowed_origins: [
      "https://preneur-social-v3.onrender.com",
      "http://localhost:4000"
    ],
    debug: true
  ],
  cache_static_manifest: "priv/static/cache_manifest.json"

config :project_social_networks, :skip_db, true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: ProjectSocialNetworks.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
