  # import Config

  # # Note we also include the path to a cache manifest
  # # containing the digested version of static files. This
  # # manifest is generated by the `mix assets.deploy` task,
  # # which you should run after static files are built and
  # # before starting your production server.
  # config :project_social_networks, ProjectSocialNetworksWeb.Endpoint,
  #   cache_static_manifest: "priv/static/cache_manifest.json"

  # # Configures Swoosh API Client
  # config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: ProjectSocialNetworks.Finch

  # # Disable Swoosh Local Memory Storage
  # config :swoosh, local: false

  # # Do not print debug messages in production
  # config :logger, level: :info

  # # Runtime production configuration, including reading
  # # of environment variables, is done on config/runtime.exs.
  import Config

  config :project_social_networks, ProjectSocialNetworksWeb.Endpoint,
    url: [host: System.get_env("PHX_HOST") || "challenge-prenuer.gigalixirapp.com", port: 443],
    http: [
      port: String.to_integer(System.get_env("PORT") || "4000"),
      transport_options: [socket_opts: [:inet6]]
    ],
    cache_static_manifest: "priv/static/cache_manifest.json",
    server: true,  # ¡Crucial para LiveView!
    secret_key_base: System.get_env("SECRET_KEY_BASE"),
    check_origin: ["//*.gigalixirapp.com", "//challenge-prenuer.gigalixirapp.com"]

  # Configuración de Swoosh
  config :swoosh,
    api_client: Swoosh.ApiClient.Finch,
    finch_name: ProjectSocialNetworks.Finch,
    local: false

  # Logger
  config :logger, level: :info

  # Configuración importante para producción
  config :phoenix, :serve_endpoints, true
  config :phoenix, :filter_parameters, ["password", "secret"]
